import Head from 'next/head';
import React, { useContext } from 'react';
import { AuthContext } from '../context/AuthContext';
import { GlobalContext } from '../context/GobalContext';
import { Footer } from './Footer';
import { NavBar as NavBarIndex } from './index/NavBar';
import { Navbar } from './Navbar';


export const Layout = ({children}:any) => {
  
  const {isLoding} = useContext(GlobalContext);
  const {isLogged} = useContext(AuthContext);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {(isLogged) ? <Navbar/> : <NavBarIndex/>}
      
      {children}


      <Footer/>
    </>
  )
}
